---
- name: Install certbot
  apt:
    name: certbot
    state: latest

- name: Install depdencies tool certbot
  apt:
    name: python3-certbot-nginx
    state: latest

#Dont forget to replace src path, match on directory
- name: Copy letsencrypt.conf to snippets
  copy:
    src: /Users/user/Desktop/deploy-laravel-terraform/ansible/conf/letsencrypt.conf
    dest: /etc/nginx/snippets

- name: Reload Nginx
  service: name=nginx state=restarted

- name: Regitser certbot
  shell: certbot -n register --agree-tos --email support@hisbul.my.id

- name: Reload nginx & Generate ssl via certbot
  shell: certbot -n --nginx -d test.hisbul.my.id