---
- name: Start Service mysql
  service:
    name: mysql
    state: started
    
- name: Update Default Root Password MySQL
  community.mysql.mysql_user: 
    name: root
    host: "{{mysql.host}}"
    password: "{{mysql.root.password}}"
    login_user: "{{mysql.root.user}}"
    login_password: "{{mysql.root.password}}"
    check_implict_admin: yes
    priv: "*.*:ALL,GRANT"

- name: Create Laravel Database
  community.mysql.mysql_db:
    name: laravel_starter
    state: present
    login_user: "{{mysql.root.user}}"
    login_password: "{{mysql.root.password}}"

- name: Create User DB laravel
  community.mysql.mysql_user:
    name: laravel
    host: "{{mysql.host}}"
    password: "{{mysql.laravel.password}}"
    login_user: "{{mysql.root.user}}"
    login_password: "{{mysql.root.password}}"
    priv: "*.laravel_starter:ALL,GRANT"