---
- name: Get Url Composer
  get_url: 
    url: https://getcomposer.org/installer
    dest: /tmp/composer

- name: Install Composer
  shell: php /tmp/composer --install-dir=/usr/local/bin

- name: Rename Composer Excutable
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer

- name: Clone Git Repository Laravel Starter
  git:
    repo: https://github.com/nasirkhan/laravel-starter.git
    dest: /var/www/laravel_starter_app

- name: Duplicate Env File
  shell: cp /var/www/laravel_starter_app/.env.example /var/www/laravel_starter_app/.env

- name: Curl public ip instance & register
  shell: curl http://169.254.169.254/latest/meta-data/public-ipv4
  register: public_ip_var

- name: Edit Env File
  lineinfile:
    path: /var/www/laravel_starter_app/.env
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  loop:
    - {regexp: 'APP_URL=http://laravel-starter.local', line: 'APP_URL={{public_ip_var.stdout}}'}
    - {regexp: 'DB_USERNAME=', line: 'DB_USERNAME=laravel'}
    - {regexp: 'DB_PASSWORD=', line: 'DB_PASSWORD={{mysql.laravel.password}}'}

- name: Run Composer Update
  community.general.composer:
    command: update
    working_dir: /var/www/laravel_starter_app
  environment:
    COMPOSER_NO_INTERACTION: "1"
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Migrate DB Laravel
  shell: |
    cd /var/www/laravel_starter_app/
    php artisan migrate --seed
    php artisan key:generate

- name: Set Required File Permission
  shell: "{{item}}"
  with_items:
   - chown -R www-data:www-data /var/www/laravel_starter_app
   - chmod -R 755 /var/www/laravel_starter_app
