---
- name: Setup Laravel App Server
  hosts: laravel
  vars_files: vars.yml
  become: true
  tasks:
    - name: Excutable all yml files
      include_tasks: "{{item}}"
      with_items:
      - pip_install.yml
      - db.yml
      - node_npm.yml
      - laravel_config.yml
      - nginx.yml
      - certbot.yml