---
- name: Setup Laravel App Server
  hosts: webserver
  become: true
  vars_files: vars.yml
  environment:
    AWS_ACCESS_KEY_ID: "{{aws.access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{aws.secret}}"
  tasks:
    - name: Excutable all yml files
      include_tasks: "{{item}}"
      with_items:
      - db.yml
      - node_npm.yml
      - laravel_config.yml
      - nginx.yml