---
- name: Create Laravel Configuration Server
  file:
    path: /etc/nginx/sites-enabled/laravel.conf
    state: touch

- name: Copy File laravel.conf to node
  copy:
    src: /Users/user/Desktop/deploy-laravel-terraform/ansible/conf/laravel_example.conf
    dest: /etc/nginx/sites-enabled

- name: Rename laravel conf
  shell: mv /etc/nginx/sites-enabled/laravel_example.conf /etc/nginx/sites-enabled/laravel.conf

- name: Curl public ip & Regitser
  shell: curl http://169.254.169.254/latest/meta-data/public-ipv4
  register: public_ip_var

- name: Edit laravel.conf
  lineinfile:
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  loop:
    - {regexp: 'server_name YOUR_DOMAIN;', line: 'server_name {{web.domain}};'}
    - {regexp: 'proxy_pass http://YOUR_DOMAIN:8000;', line: 'proxy_pass http://{{public_ip_var}};'}

- name: Copy laravel.conf to sites-avalaible
  shell: sudo ln /etc/nginx/sites-enabled/laravel.conf /etc/nginx/sites-available

- name: Unlink Default Configuration & Check Configuration Nginx
  shell: |
    unlink /etc/nginx/sites-enabled/default
    unlink /etc/nginx/sites-available/default
    nginx -t

- name: Reload Nginx
  service: name=nginx state=restarted

